/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import com.sun.org.apache.xml.internal.utils.NameSpace;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTextArea;
import utils.DbConnection;

/**
 *
 * @author Rishabh
 */
public class History extends javax.swing.JFrame {
    
    /**
     * Creates new form History
     */
    int [] spent = new int[4];
    String[] names = {"Rahul","Rishabh","Pranav","Pandey"};
    
    public History() {
        initComponents();
        DbConnection dbConnection = new DbConnection();
        ResultSet res = dbConnection.runQuery("SELECT * FROM main");
        String date, name, paidBy, amount,finalRes = "\t Date \tTitle \tPaid By \tAmount\n";
        finalRes+="\t-----------------------------------------------------------------------------------\n\n";
        try {
            while (res.next()) {
                date = res.getString("date");
                name = res.getString("title");
                amount = res.getString("amount");
                paidBy = res.getString("paid_by");
                for(int i=0;i<4;i++)
                    if(paidBy.equals(names[i]))
                        spent[i]+=Integer.parseInt(amount);
                finalRes+="\t" + date+"\t"+name+"\t"+paidBy+"\t"+amount+"\n\n";
            }

        } catch (SQLException ex) { 
            System.err.println(ex);
        }
        finalRes+="\n---------------------------------------------------------------------------------------------------------\n";
        for (int i = 0; i < 4; i++)
            finalRes += "\n\n\t" + names[i] + "\tpaid" + " \t" + spent[i];

        JTextArea jTextArea  = new JTextArea(finalRes);
        jTextArea.setBounds(100, 50, 500, 600);
        jTextArea.setEditable(false);
        add(jTextArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(516, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
